// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(1)
FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminSession = `-- name: CreateAdminSession :exec
INSERT INTO admin_sessions (token, admin_id, issued_at, expires_at, revoked, last_seen)
VALUES (?, ?, ?, ?, 0, ?)
`

type CreateAdminSessionParams struct {
	Token     string       `json:"token"`
	AdminID   int64        `json:"admin_id"`
	IssuedAt  time.Time    `json:"issued_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	LastSeen  sql.NullTime `json:"last_seen"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdminSession,
		arg.Token,
		arg.AdminID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastSeen,
	)
	return err
}

const createAdminUser = `-- name: CreateAdminUser :exec
INSERT INTO admin_users (username, password_hash, display_name)
VALUES (?, ?, ?)
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error {
	_, err := q.db.ExecContext(ctx, createAdminUser, arg.Username, arg.PasswordHash, arg.DisplayName)
	return err
}

const getAdminSession = `-- name: GetAdminSession :one
SELECT token, admin_id, issued_at, expires_at, revoked, last_seen
FROM admin_sessions
WHERE token = ?
LIMIT 1
`

func (q *Queries) GetAdminSession(ctx context.Context, token string) (AdminSession, error) {
	row := q.db.QueryRowContext(ctx, getAdminSession, token)
	var i AdminSession
	err := row.Scan(
		&i.Token,
		&i.AdminID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastSeen,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, display_name, created_at
FROM admin_users
WHERE username = ?
LIMIT 1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions
SET revoked = 1
WHERE token = ?
`

func (q *Queries) RevokeAdminSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeAdminSession, token)
	return err
}

const updateAdminSessionLastSeen = `-- name: UpdateAdminSessionLastSeen :exec
UPDATE admin_sessions
SET last_seen = ?
WHERE token = ?
`

type UpdateAdminSessionLastSeenParams struct {
	LastSeen sql.NullTime `json:"last_seen"`
	Token    string       `json:"token"`
}

func (q *Queries) UpdateAdminSessionLastSeen(ctx context.Context, arg UpdateAdminSessionLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateAdminSessionLastSeen, arg.LastSeen, arg.Token)
	return err
}
