// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (operator_id, action, target_type, target_id, detail)
VALUES (?, ?, ?, ?, ?)
`

type CreateAuditLogParams struct {
	OperatorID int64           `json:"operator_id"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   sql.NullInt64   `json:"target_id"`
	Detail     json.RawMessage `json:"detail"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.OperatorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, operator_id, action, target_type, target_id, COALESCE(detail, JSON_OBJECT()) AS detail, created_at
FROM audit_logs
ORDER BY id DESC
LIMIT 200
`

func (q *Queries) ListAuditLogs(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByRange = `-- name: ListAuditLogsByRange :many
SELECT id, operator_id, action, target_type, target_id, COALESCE(detail, JSON_OBJECT()) AS detail, created_at
FROM audit_logs
WHERE created_at >= ?
  AND created_at < ?
ORDER BY created_at DESC, id DESC
LIMIT 200
`

type ListAuditLogsByRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) ListAuditLogsByRange(ctx context.Context, arg ListAuditLogsByRangeParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
