// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_stats.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addDailyStats = `-- name: AddDailyStats :exec
INSERT INTO daily_stats (
  stat_date,
  employee_id,
  work_seconds,
  normal_seconds,
  fish_seconds,
  idle_seconds,
  offline_seconds,
  attendance_seconds,
  effective_seconds
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  work_seconds = GREATEST(0, work_seconds + VALUES(work_seconds)),
  normal_seconds = GREATEST(0, normal_seconds + VALUES(normal_seconds)),
  fish_seconds = GREATEST(0, fish_seconds + VALUES(fish_seconds)),
  idle_seconds = GREATEST(0, idle_seconds + VALUES(idle_seconds)),
  offline_seconds = GREATEST(0, offline_seconds + VALUES(offline_seconds)),
  attendance_seconds = GREATEST(0, attendance_seconds + VALUES(attendance_seconds)),
  effective_seconds = GREATEST(0, effective_seconds + VALUES(effective_seconds))
`

type AddDailyStatsParams struct {
	StatDate          time.Time `json:"stat_date"`
	EmployeeID        int64     `json:"employee_id"`
	WorkSeconds       int32     `json:"work_seconds"`
	NormalSeconds     int32     `json:"normal_seconds"`
	FishSeconds       int32     `json:"fish_seconds"`
	IdleSeconds       int32     `json:"idle_seconds"`
	OfflineSeconds    int32     `json:"offline_seconds"`
	AttendanceSeconds int32     `json:"attendance_seconds"`
	EffectiveSeconds  int32     `json:"effective_seconds"`
}

func (q *Queries) AddDailyStats(ctx context.Context, arg AddDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, addDailyStats,
		arg.StatDate,
		arg.EmployeeID,
		arg.WorkSeconds,
		arg.NormalSeconds,
		arg.FishSeconds,
		arg.IdleSeconds,
		arg.OfflineSeconds,
		arg.AttendanceSeconds,
		arg.EffectiveSeconds,
	)
	return err
}

const listDailyStatsByDate = `-- name: ListDailyStatsByDate :many
SELECT ds.stat_date,
       e.employee_code,
       e.name,
       d.name AS department_name,
       ds.work_seconds,
       ds.normal_seconds,
       ds.fish_seconds,
       ds.idle_seconds,
       ds.offline_seconds,
       ds.attendance_seconds,
       ds.effective_seconds,
       CAST(COALESCE(breaks.break_seconds, 0) AS SIGNED) AS break_seconds,
       CAST(COALESCE(on_duty.on_duty_seconds, 0) AS SIGNED) AS on_duty_seconds
FROM daily_stats ds
JOIN employees e ON ds.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
LEFT JOIN (
  SELECT ts.employee_id,
         SUM(TIMESTAMPDIFF(SECOND, GREATEST(ts.start_at, ?), LEAST(ts.end_at, ?))) AS break_seconds
  FROM time_segments ts
  WHERE ts.status = 'break'
    AND ts.start_at < ?
    AND ts.end_at > ?
  GROUP BY ts.employee_id
) breaks ON breaks.employee_id = ds.employee_id
LEFT JOIN (
  SELECT ws.employee_id,
         SUM(TIMESTAMPDIFF(SECOND, GREATEST(ws.start_at, ?), LEAST(COALESCE(ws.end_at, ?), ?))) AS on_duty_seconds
  FROM work_sessions ws
  WHERE ws.start_at < ?
    AND COALESCE(ws.end_at, ?) > ?
  GROUP BY ws.employee_id
) on_duty ON on_duty.employee_id = ds.employee_id
WHERE ds.stat_date = ?
  AND (? = 0 OR e.department_id = ?)
ORDER BY ds.attendance_seconds DESC
`

type ListDailyStatsByDateParams struct {
	GREATEST     interface{}   `json:"GREATEST"`
	LEAST        interface{}   `json:"LEAST"`
	StartAt      time.Time     `json:"start_at"`
	EndAt        time.Time     `json:"end_at"`
	GREATEST_2   interface{}   `json:"GREATEST_2"`
	Column6      interface{}   `json:"column_6"`
	LEAST_2      interface{}   `json:"LEAST_2"`
	StartAt_2    time.Time     `json:"start_at_2"`
	EndAt_2      sql.NullTime  `json:"end_at_2"`
	EndAt_3      sql.NullTime  `json:"end_at_3"`
	StatDate     time.Time     `json:"stat_date"`
	Column12     interface{}   `json:"column_12"`
	DepartmentID sql.NullInt64 `json:"department_id"`
}

type ListDailyStatsByDateRow struct {
	StatDate          time.Time      `json:"stat_date"`
	EmployeeCode      string         `json:"employee_code"`
	Name              string         `json:"name"`
	DepartmentName    sql.NullString `json:"department_name"`
	WorkSeconds       int32          `json:"work_seconds"`
	NormalSeconds     int32          `json:"normal_seconds"`
	FishSeconds       int32          `json:"fish_seconds"`
	IdleSeconds       int32          `json:"idle_seconds"`
	OfflineSeconds    int32          `json:"offline_seconds"`
	AttendanceSeconds int32          `json:"attendance_seconds"`
	EffectiveSeconds  int32          `json:"effective_seconds"`
	BreakSeconds      int64          `json:"break_seconds"`
	OnDutySeconds     int64          `json:"on_duty_seconds"`
}

func (q *Queries) ListDailyStatsByDate(ctx context.Context, arg ListDailyStatsByDateParams) ([]ListDailyStatsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsByDate,
		arg.GREATEST,
		arg.LEAST,
		arg.StartAt,
		arg.EndAt,
		arg.GREATEST_2,
		arg.Column6,
		arg.LEAST_2,
		arg.StartAt_2,
		arg.EndAt_2,
		arg.EndAt_3,
		arg.StatDate,
		arg.Column12,
		arg.DepartmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyStatsByDateRow
	for rows.Next() {
		var i ListDailyStatsByDateRow
		if err := rows.Scan(
			&i.StatDate,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.WorkSeconds,
			&i.NormalSeconds,
			&i.FishSeconds,
			&i.IdleSeconds,
			&i.OfflineSeconds,
			&i.AttendanceSeconds,
			&i.EffectiveSeconds,
			&i.BreakSeconds,
			&i.OnDutySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyStatsForExportByDate = `-- name: ListDailyStatsForExportByDate :many
SELECT ds.stat_date,
       e.employee_code,
       e.name,
       d.name AS department_name,
       ds.work_seconds,
       ds.normal_seconds,
       ds.fish_seconds,
       ds.idle_seconds,
       ds.offline_seconds,
       ds.attendance_seconds,
       ds.effective_seconds,
       CAST(COALESCE(breaks.break_seconds, 0) AS SIGNED) AS break_seconds,
       CAST(COALESCE(on_duty.on_duty_seconds, 0) AS SIGNED) AS on_duty_seconds,
       ws_start.first_start_at,
       ws_end.last_end_at
FROM daily_stats ds
JOIN employees e ON ds.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
LEFT JOIN (
  SELECT ts.employee_id,
         SUM(TIMESTAMPDIFF(SECOND, GREATEST(ts.start_at, ?), LEAST(ts.end_at, ?))) AS break_seconds
  FROM time_segments ts
  WHERE ts.status = 'break'
    AND ts.start_at < ?
    AND ts.end_at > ?
  GROUP BY ts.employee_id
) breaks ON breaks.employee_id = ds.employee_id
LEFT JOIN (
  SELECT ws.employee_id,
         SUM(TIMESTAMPDIFF(SECOND, GREATEST(ws.start_at, ?), LEAST(COALESCE(ws.end_at, ?), ?))) AS on_duty_seconds
  FROM work_sessions ws
  WHERE ws.start_at < ?
    AND COALESCE(ws.end_at, ?) > ?
  GROUP BY ws.employee_id
) on_duty ON on_duty.employee_id = ds.employee_id
LEFT JOIN (
  SELECT ws.employee_id,
         MIN(ws.start_at) AS first_start_at
  FROM work_sessions ws
  WHERE ws.start_at >= ?
    AND ws.start_at < ?
  GROUP BY ws.employee_id
) ws_start ON ws_start.employee_id = ds.employee_id
LEFT JOIN (
  SELECT ws.employee_id,
         MAX(ws.end_at) AS last_end_at
  FROM work_sessions ws
  WHERE ws.end_at IS NOT NULL
    AND ws.end_at >= ?
    AND ws.end_at < ?
  GROUP BY ws.employee_id
) ws_end ON ws_end.employee_id = ds.employee_id
WHERE ds.stat_date = ?
  AND (? = 0 OR e.department_id = ?)
ORDER BY ds.attendance_seconds DESC
`

type ListDailyStatsForExportByDateParams struct {
	GREATEST     interface{}   `json:"GREATEST"`
	LEAST        interface{}   `json:"LEAST"`
	StartAt      time.Time     `json:"start_at"`
	EndAt        time.Time     `json:"end_at"`
	GREATEST_2   interface{}   `json:"GREATEST_2"`
	Column6      interface{}   `json:"column_6"`
	LEAST_2      interface{}   `json:"LEAST_2"`
	StartAt_2    time.Time     `json:"start_at_2"`
	EndAt_2      sql.NullTime  `json:"end_at_2"`
	EndAt_3      sql.NullTime  `json:"end_at_3"`
	StartAt_3    time.Time     `json:"start_at_3"`
	StartAt_4    time.Time     `json:"start_at_4"`
	EndAt_4      sql.NullTime  `json:"end_at_4"`
	EndAt_5      sql.NullTime  `json:"end_at_5"`
	StatDate     time.Time     `json:"stat_date"`
	Column16     interface{}   `json:"column_16"`
	DepartmentID sql.NullInt64 `json:"department_id"`
}

type ListDailyStatsForExportByDateRow struct {
	StatDate          time.Time      `json:"stat_date"`
	EmployeeCode      string         `json:"employee_code"`
	Name              string         `json:"name"`
	DepartmentName    sql.NullString `json:"department_name"`
	WorkSeconds       int32          `json:"work_seconds"`
	NormalSeconds     int32          `json:"normal_seconds"`
	FishSeconds       int32          `json:"fish_seconds"`
	IdleSeconds       int32          `json:"idle_seconds"`
	OfflineSeconds    int32          `json:"offline_seconds"`
	AttendanceSeconds int32          `json:"attendance_seconds"`
	EffectiveSeconds  int32          `json:"effective_seconds"`
	BreakSeconds      int64          `json:"break_seconds"`
	OnDutySeconds     int64          `json:"on_duty_seconds"`
	FirstStartAt      interface{}    `json:"first_start_at"`
	LastEndAt         interface{}    `json:"last_end_at"`
}

func (q *Queries) ListDailyStatsForExportByDate(ctx context.Context, arg ListDailyStatsForExportByDateParams) ([]ListDailyStatsForExportByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsForExportByDate,
		arg.GREATEST,
		arg.LEAST,
		arg.StartAt,
		arg.EndAt,
		arg.GREATEST_2,
		arg.Column6,
		arg.LEAST_2,
		arg.StartAt_2,
		arg.EndAt_2,
		arg.EndAt_3,
		arg.StartAt_3,
		arg.StartAt_4,
		arg.EndAt_4,
		arg.EndAt_5,
		arg.StatDate,
		arg.Column16,
		arg.DepartmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyStatsForExportByDateRow
	for rows.Next() {
		var i ListDailyStatsForExportByDateRow
		if err := rows.Scan(
			&i.StatDate,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.WorkSeconds,
			&i.NormalSeconds,
			&i.FishSeconds,
			&i.IdleSeconds,
			&i.OfflineSeconds,
			&i.AttendanceSeconds,
			&i.EffectiveSeconds,
			&i.BreakSeconds,
			&i.OnDutySeconds,
			&i.FirstStartAt,
			&i.LastEndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
