// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_stats.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addDailyStats = `-- name: AddDailyStats :exec
INSERT INTO daily_stats (
  stat_date,
  employee_id,
  work_seconds,
  normal_seconds,
  fish_seconds,
  idle_seconds,
  offline_seconds,
  attendance_seconds,
  effective_seconds
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
  work_seconds = GREATEST(0, work_seconds + VALUES(work_seconds)),
  normal_seconds = GREATEST(0, normal_seconds + VALUES(normal_seconds)),
  fish_seconds = GREATEST(0, fish_seconds + VALUES(fish_seconds)),
  idle_seconds = GREATEST(0, idle_seconds + VALUES(idle_seconds)),
  offline_seconds = GREATEST(0, offline_seconds + VALUES(offline_seconds)),
  attendance_seconds = GREATEST(0, attendance_seconds + VALUES(attendance_seconds)),
  effective_seconds = GREATEST(0, effective_seconds + VALUES(effective_seconds))
`

type AddDailyStatsParams struct {
	StatDate          time.Time `json:"stat_date"`
	EmployeeID        int64     `json:"employee_id"`
	WorkSeconds       int32     `json:"work_seconds"`
	NormalSeconds     int32     `json:"normal_seconds"`
	FishSeconds       int32     `json:"fish_seconds"`
	IdleSeconds       int32     `json:"idle_seconds"`
	OfflineSeconds    int32     `json:"offline_seconds"`
	AttendanceSeconds int32     `json:"attendance_seconds"`
	EffectiveSeconds  int32     `json:"effective_seconds"`
}

func (q *Queries) AddDailyStats(ctx context.Context, arg AddDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, addDailyStats,
		arg.StatDate,
		arg.EmployeeID,
		arg.WorkSeconds,
		arg.NormalSeconds,
		arg.FishSeconds,
		arg.IdleSeconds,
		arg.OfflineSeconds,
		arg.AttendanceSeconds,
		arg.EffectiveSeconds,
	)
	return err
}

const listDailyStatsByDate = `-- name: ListDailyStatsByDate :many
SELECT ds.stat_date,
       e.employee_code,
       e.name,
       d.name AS department_name,
       ds.work_seconds,
       ds.normal_seconds,
       ds.fish_seconds,
       ds.idle_seconds,
       ds.offline_seconds,
       ds.attendance_seconds,
       ds.effective_seconds,
       CAST(COALESCE((
         SELECT SUM(TIMESTAMPDIFF(
           SECOND,
           GREATEST(ts.start_at, ?),
           LEAST(ts.end_at, ?)
         ))
         FROM time_segments ts FORCE INDEX (idx_time_segments_employee_end)
         WHERE ts.employee_id = ds.employee_id
           AND ts.status = 'break'
           AND ts.start_at < ?
           AND ts.end_at > ?
       ), 0) AS SIGNED) AS break_seconds,
       CAST(COALESCE((
         SELECT SUM(TIMESTAMPDIFF(
           SECOND,
           GREATEST(ws.start_at, ?),
           LEAST(COALESCE(ws.end_at, ?), ?)
         ))
         FROM work_sessions ws FORCE INDEX (idx_work_sessions_employee_end)
         WHERE ws.employee_id = ds.employee_id
           AND ws.start_at < ?
           AND (ws.end_at IS NULL OR ws.end_at > ?)
       ), 0) AS SIGNED) AS on_duty_seconds
FROM daily_stats ds
JOIN employees e ON ds.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
WHERE ds.stat_date = ?
  AND (? = 0 OR e.department_id = ?)
ORDER BY ds.attendance_seconds DESC
`

type ListDailyStatsByDateParams struct {
	DayStart           time.Time     `json:"day_start"`
	ReportEnd          time.Time     `json:"report_end"`
	StatDate           time.Time     `json:"stat_date"`
	DepartmentIDFilter int64         `json:"department_id_filter"`
	DepartmentID       sql.NullInt64 `json:"department_id"`
}

type ListDailyStatsByDateRow struct {
	StatDate          time.Time      `json:"stat_date"`
	EmployeeCode      string         `json:"employee_code"`
	Name              string         `json:"name"`
	DepartmentName    sql.NullString `json:"department_name"`
	WorkSeconds       int32          `json:"work_seconds"`
	NormalSeconds     int32          `json:"normal_seconds"`
	FishSeconds       int32          `json:"fish_seconds"`
	IdleSeconds       int32          `json:"idle_seconds"`
	OfflineSeconds    int32          `json:"offline_seconds"`
	AttendanceSeconds int32          `json:"attendance_seconds"`
	EffectiveSeconds  int32          `json:"effective_seconds"`
	BreakSeconds      int64          `json:"break_seconds"`
	OnDutySeconds     int64          `json:"on_duty_seconds"`
}

func (q *Queries) ListDailyStatsByDate(ctx context.Context, arg ListDailyStatsByDateParams) ([]ListDailyStatsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsByDate,
		arg.DayStart,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.DayStart,
		arg.DayStart,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.DayStart,
		arg.StatDate,
		arg.DepartmentIDFilter,
		arg.DepartmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyStatsByDateRow
	for rows.Next() {
		var i ListDailyStatsByDateRow
		if err := rows.Scan(
			&i.StatDate,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.WorkSeconds,
			&i.NormalSeconds,
			&i.FishSeconds,
			&i.IdleSeconds,
			&i.OfflineSeconds,
			&i.AttendanceSeconds,
			&i.EffectiveSeconds,
			&i.BreakSeconds,
			&i.OnDutySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyStatsForRankByDate = `-- name: ListDailyStatsForRankByDate :many
SELECT e.employee_code,
       e.name,
       d.name AS department_name,
       ds.fish_seconds,
       ds.attendance_seconds,
       ds.effective_seconds
FROM daily_stats ds
JOIN employees e ON ds.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
WHERE ds.stat_date = ?
`

type ListDailyStatsForRankByDateRow struct {
	EmployeeCode      string         `json:"employee_code"`
	Name              string         `json:"name"`
	DepartmentName    sql.NullString `json:"department_name"`
	FishSeconds       int32          `json:"fish_seconds"`
	AttendanceSeconds int32          `json:"attendance_seconds"`
	EffectiveSeconds  int32          `json:"effective_seconds"`
}

func (q *Queries) ListDailyStatsForRankByDate(ctx context.Context, statDate time.Time) ([]ListDailyStatsForRankByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsForRankByDate, statDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyStatsForRankByDateRow
	for rows.Next() {
		var i ListDailyStatsForRankByDateRow
		if err := rows.Scan(
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.FishSeconds,
			&i.AttendanceSeconds,
			&i.EffectiveSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyStatsForExportByDate = `-- name: ListDailyStatsForExportByDate :many
SELECT ds.stat_date,
       e.employee_code,
       e.name,
       d.name AS department_name,
       ds.work_seconds,
       ds.normal_seconds,
       ds.fish_seconds,
       ds.idle_seconds,
       ds.offline_seconds,
       ds.attendance_seconds,
       ds.effective_seconds,
       CAST(COALESCE((
         SELECT SUM(TIMESTAMPDIFF(
           SECOND,
           GREATEST(ts.start_at, ?),
           LEAST(ts.end_at, ?)
         ))
         FROM time_segments ts FORCE INDEX (idx_time_segments_employee_end)
         WHERE ts.employee_id = ds.employee_id
           AND ts.status = 'break'
           AND ts.start_at < ?
           AND ts.end_at > ?
       ), 0) AS SIGNED) AS break_seconds,
       CAST(COALESCE((
         SELECT SUM(TIMESTAMPDIFF(
           SECOND,
           GREATEST(ws.start_at, ?),
           LEAST(COALESCE(ws.end_at, ?), ?)
         ))
         FROM work_sessions ws FORCE INDEX (idx_work_sessions_employee_end)
         WHERE ws.employee_id = ds.employee_id
           AND ws.start_at < ?
           AND (ws.end_at IS NULL OR ws.end_at > ?)
       ), 0) AS SIGNED) AS on_duty_seconds,
       (
         SELECT MIN(ws_start.start_at)
         FROM work_sessions ws_start FORCE INDEX (idx_work_sessions_employee_start)
         WHERE ws_start.employee_id = ds.employee_id
           AND ws_start.start_at >= ?
           AND ws_start.start_at < ?
       ) AS first_start_at,
       (
         SELECT MAX(ws_end.end_at)
         FROM work_sessions ws_end FORCE INDEX (idx_work_sessions_employee_end)
         WHERE ws_end.employee_id = ds.employee_id
           AND ws_end.end_at >= ?
           AND ws_end.end_at < ?
       ) AS last_end_at
FROM daily_stats ds
JOIN employees e ON ds.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
WHERE ds.stat_date = ?
  AND (? = 0 OR e.department_id = ?)
ORDER BY ds.attendance_seconds DESC
`

type ListDailyStatsForExportByDateParams struct {
	DayStart           time.Time     `json:"day_start"`
	ReportEnd          time.Time     `json:"report_end"`
	DayEnd             time.Time     `json:"day_end"`
	StatDate           time.Time     `json:"stat_date"`
	DepartmentIDFilter int64         `json:"department_id_filter"`
	DepartmentID       sql.NullInt64 `json:"department_id"`
}

type ListDailyStatsForExportByDateRow struct {
	StatDate          time.Time      `json:"stat_date"`
	EmployeeCode      string         `json:"employee_code"`
	Name              string         `json:"name"`
	DepartmentName    sql.NullString `json:"department_name"`
	WorkSeconds       int32          `json:"work_seconds"`
	NormalSeconds     int32          `json:"normal_seconds"`
	FishSeconds       int32          `json:"fish_seconds"`
	IdleSeconds       int32          `json:"idle_seconds"`
	OfflineSeconds    int32          `json:"offline_seconds"`
	AttendanceSeconds int32          `json:"attendance_seconds"`
	EffectiveSeconds  int32          `json:"effective_seconds"`
	BreakSeconds      int64          `json:"break_seconds"`
	OnDutySeconds     int64          `json:"on_duty_seconds"`
	FirstStartAt      interface{}    `json:"first_start_at"`
	LastEndAt         interface{}    `json:"last_end_at"`
}

func (q *Queries) ListDailyStatsForExportByDate(ctx context.Context, arg ListDailyStatsForExportByDateParams) ([]ListDailyStatsForExportByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsForExportByDate,
		arg.DayStart,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.DayStart,
		arg.DayStart,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.ReportEnd,
		arg.DayStart,
		arg.DayStart,
		arg.DayEnd,
		arg.DayStart,
		arg.DayEnd,
		arg.StatDate,
		arg.DepartmentIDFilter,
		arg.DepartmentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyStatsForExportByDateRow
	for rows.Next() {
		var i ListDailyStatsForExportByDateRow
		if err := rows.Scan(
			&i.StatDate,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.WorkSeconds,
			&i.NormalSeconds,
			&i.FishSeconds,
			&i.IdleSeconds,
			&i.OfflineSeconds,
			&i.AttendanceSeconds,
			&i.EffectiveSeconds,
			&i.BreakSeconds,
			&i.OnDutySeconds,
			&i.FirstStartAt,
			&i.LastEndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
