// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countEmployeesByDepartment = `-- name: CountEmployeesByDepartment :one
SELECT COUNT(1)
FROM employees
WHERE department_id = ?
`

func (q *Queries) CountEmployeesByDepartment(ctx context.Context, departmentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmployeesByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :exec
INSERT INTO departments (name, parent_id)
VALUES (?, ?)
`

type CreateDepartmentParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, createDepartment, arg.Name, arg.ParentID)
	return err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = ?
`

func (q *Queries) DeleteDepartment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, id)
	return err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, parent_id, created_at
FROM departments
ORDER BY id DESC
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :exec
UPDATE departments
SET name = ?, parent_id = ?
WHERE id = ?
`

type UpdateDepartmentParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, updateDepartment, arg.Name, arg.ParentID, arg.ID)
	return err
}
