// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT id, employee_code, name, department_id, fingerprint_hash, enabled, last_seen_at, last_status, last_description, current_segment_started_at, last_segment_end_at, created_at
FROM employees
WHERE employee_code = ?
LIMIT 1
`

type GetEmployeeByCodeRow struct {
	ID                      int64                   `json:"id"`
	EmployeeCode            string                  `json:"employee_code"`
	Name                    string                  `json:"name"`
	DepartmentID            sql.NullInt64           `json:"department_id"`
	FingerprintHash         sql.NullString          `json:"fingerprint_hash"`
	Enabled                 bool                    `json:"enabled"`
	LastSeenAt              sql.NullTime            `json:"last_seen_at"`
	LastStatus              NullEmployeesLastStatus `json:"last_status"`
	LastDescription         sql.NullString          `json:"last_description"`
	CurrentSegmentStartedAt sql.NullTime            `json:"current_segment_started_at"`
	LastSegmentEndAt        sql.NullTime            `json:"last_segment_end_at"`
	CreatedAt               time.Time               `json:"created_at"`
}

func (q *Queries) GetEmployeeByCode(ctx context.Context, employeeCode string) (GetEmployeeByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByCode, employeeCode)
	var i GetEmployeeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Name,
		&i.DepartmentID,
		&i.FingerprintHash,
		&i.Enabled,
		&i.LastSeenAt,
		&i.LastStatus,
		&i.LastDescription,
		&i.CurrentSegmentStartedAt,
		&i.LastSegmentEndAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, employee_code, name, department_id, fingerprint_hash, enabled, last_seen_at, last_status, last_description, current_segment_started_at, last_segment_end_at, created_at
FROM employees
WHERE id = ?
LIMIT 1
`

type GetEmployeeByIDRow struct {
	ID                      int64                   `json:"id"`
	EmployeeCode            string                  `json:"employee_code"`
	Name                    string                  `json:"name"`
	DepartmentID            sql.NullInt64           `json:"department_id"`
	FingerprintHash         sql.NullString          `json:"fingerprint_hash"`
	Enabled                 bool                    `json:"enabled"`
	LastSeenAt              sql.NullTime            `json:"last_seen_at"`
	LastStatus              NullEmployeesLastStatus `json:"last_status"`
	LastDescription         sql.NullString          `json:"last_description"`
	CurrentSegmentStartedAt sql.NullTime            `json:"current_segment_started_at"`
	LastSegmentEndAt        sql.NullTime            `json:"last_segment_end_at"`
	CreatedAt               time.Time               `json:"created_at"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.Name,
		&i.DepartmentID,
		&i.FingerprintHash,
		&i.Enabled,
		&i.LastSeenAt,
		&i.LastStatus,
		&i.LastDescription,
		&i.CurrentSegmentStartedAt,
		&i.LastSegmentEndAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, employee_code, name, department_id, enabled
FROM employees
WHERE enabled = 1
ORDER BY id DESC
`

type ListEmployeesRow struct {
	ID           int64         `json:"id"`
	EmployeeCode string        `json:"employee_code"`
	Name         string        `json:"name"`
	DepartmentID sql.NullInt64 `json:"department_id"`
	Enabled      bool          `json:"enabled"`
}

func (q *Queries) ListEmployees(ctx context.Context) ([]ListEmployeesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentID,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesForOfflineRefresh = `-- name: ListEmployeesForOfflineRefresh :many
SELECT id, employee_code, name, department_id, fingerprint_hash, enabled, last_seen_at, last_status, last_description, current_segment_started_at, last_segment_end_at, created_at
FROM employees
WHERE enabled = 1
  AND last_seen_at IS NOT NULL
`

type ListEmployeesForOfflineRefreshRow struct {
	ID                      int64                   `json:"id"`
	EmployeeCode            string                  `json:"employee_code"`
	Name                    string                  `json:"name"`
	DepartmentID            sql.NullInt64           `json:"department_id"`
	FingerprintHash         sql.NullString          `json:"fingerprint_hash"`
	Enabled                 bool                    `json:"enabled"`
	LastSeenAt              sql.NullTime            `json:"last_seen_at"`
	LastStatus              NullEmployeesLastStatus `json:"last_status"`
	LastDescription         sql.NullString          `json:"last_description"`
	CurrentSegmentStartedAt sql.NullTime            `json:"current_segment_started_at"`
	LastSegmentEndAt        sql.NullTime            `json:"last_segment_end_at"`
	CreatedAt               time.Time               `json:"created_at"`
}

func (q *Queries) ListEmployeesForOfflineRefresh(ctx context.Context) ([]ListEmployeesForOfflineRefreshRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesForOfflineRefresh)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeesForOfflineRefreshRow
	for rows.Next() {
		var i ListEmployeesForOfflineRefreshRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentID,
			&i.FingerprintHash,
			&i.Enabled,
			&i.LastSeenAt,
			&i.LastStatus,
			&i.LastDescription,
			&i.CurrentSegmentStartedAt,
			&i.LastSegmentEndAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeFingerprint = `-- name: UpdateEmployeeFingerprint :exec
UPDATE employees
SET fingerprint_hash = ?
WHERE id = ?
`

type UpdateEmployeeFingerprintParams struct {
	FingerprintHash sql.NullString `json:"fingerprint_hash"`
	ID              int64          `json:"id"`
}

func (q *Queries) UpdateEmployeeFingerprint(ctx context.Context, arg UpdateEmployeeFingerprintParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeFingerprint, arg.FingerprintHash, arg.ID)
	return err
}

const updateEmployeeTrackingState = `-- name: UpdateEmployeeTrackingState :exec
UPDATE employees
SET last_seen_at = ?,
    last_status = ?,
    last_description = ?,
    current_segment_started_at = ?,
    last_segment_end_at = ?
WHERE id = ?
`

type UpdateEmployeeTrackingStateParams struct {
	LastSeenAt              sql.NullTime            `json:"last_seen_at"`
	LastStatus              NullEmployeesLastStatus `json:"last_status"`
	LastDescription         sql.NullString          `json:"last_description"`
	CurrentSegmentStartedAt sql.NullTime            `json:"current_segment_started_at"`
	LastSegmentEndAt        sql.NullTime            `json:"last_segment_end_at"`
	ID                      int64                   `json:"id"`
}

func (q *Queries) UpdateEmployeeTrackingState(ctx context.Context, arg UpdateEmployeeTrackingStateParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeTrackingState,
		arg.LastSeenAt,
		arg.LastStatus,
		arg.LastDescription,
		arg.CurrentSegmentStartedAt,
		arg.LastSegmentEndAt,
		arg.ID,
	)
	return err
}
