// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: live_snapshot.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listLiveSnapshot = `-- name: ListLiveSnapshot :many
SELECT e.employee_code,
       e.name,
       d.name AS department_name,
       e.last_status,
       e.last_description,
       e.last_seen_at
FROM employees e
LEFT JOIN departments d ON e.department_id = d.id
WHERE e.enabled = 1
ORDER BY e.id DESC
`

type ListLiveSnapshotRow struct {
	EmployeeCode    string                  `json:"employee_code"`
	Name            string                  `json:"name"`
	DepartmentName  sql.NullString          `json:"department_name"`
	LastStatus      NullEmployeesLastStatus `json:"last_status"`
	LastDescription sql.NullString          `json:"last_description"`
	LastSeenAt      sql.NullTime            `json:"last_seen_at"`
}

func (q *Queries) ListLiveSnapshot(ctx context.Context) ([]ListLiveSnapshotRow, error) {
	rows, err := q.db.QueryContext(ctx, listLiveSnapshot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveSnapshotRow
	for rows.Next() {
		var i ListLiveSnapshotRow
		if err := rows.Scan(
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
			&i.LastStatus,
			&i.LastDescription,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
