// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manual_adjustments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createManualAdjustment = `-- name: CreateManualAdjustment :execresult
INSERT INTO manual_adjustments (
  employee_id,
  start_at,
  end_at,
  reason,
  note,
  operator_id,
  status
) VALUES (?, ?, ?, ?, ?, ?, 'active')
`

type CreateManualAdjustmentParams struct {
	EmployeeID int64     `json:"employee_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
	Reason     string    `json:"reason"`
	Note       string    `json:"note"`
	OperatorID int64     `json:"operator_id"`
}

func (q *Queries) CreateManualAdjustment(ctx context.Context, arg CreateManualAdjustmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createManualAdjustment,
		arg.EmployeeID,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
		arg.Note,
		arg.OperatorID,
	)
}

const getManualAdjustment = `-- name: GetManualAdjustment :one
SELECT id, employee_id, start_at, end_at, reason, note, operator_id, status, created_at, updated_at
FROM manual_adjustments
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetManualAdjustment(ctx context.Context, id int64) (ManualAdjustment, error) {
	row := q.db.QueryRowContext(ctx, getManualAdjustment, id)
	var i ManualAdjustment
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartAt,
		&i.EndAt,
		&i.Reason,
		&i.Note,
		&i.OperatorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManualAdjustments = `-- name: ListManualAdjustments :many
SELECT ma.id, ma.start_at, ma.end_at, ma.reason, ma.note, ma.operator_id, ma.status, ma.created_at,
       e.employee_code, e.name, d.name AS department_name
FROM manual_adjustments ma
JOIN employees e ON ma.employee_id = e.id
LEFT JOIN departments d ON e.department_id = d.id
WHERE ( ? = '' OR DATE(ma.start_at) = ? )
ORDER BY ma.created_at DESC
`

type ListManualAdjustmentsParams struct {
	Column1 interface{} `json:"column_1"`
	StartAt time.Time   `json:"start_at"`
}

type ListManualAdjustmentsRow struct {
	ID             int64                   `json:"id"`
	StartAt        time.Time               `json:"start_at"`
	EndAt          time.Time               `json:"end_at"`
	Reason         string                  `json:"reason"`
	Note           string                  `json:"note"`
	OperatorID     int64                   `json:"operator_id"`
	Status         ManualAdjustmentsStatus `json:"status"`
	CreatedAt      time.Time               `json:"created_at"`
	EmployeeCode   string                  `json:"employee_code"`
	Name           string                  `json:"name"`
	DepartmentName sql.NullString          `json:"department_name"`
}

func (q *Queries) ListManualAdjustments(ctx context.Context, arg ListManualAdjustmentsParams) ([]ListManualAdjustmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listManualAdjustments, arg.Column1, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListManualAdjustmentsRow
	for rows.Next() {
		var i ListManualAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.Reason,
			&i.Note,
			&i.OperatorID,
			&i.Status,
			&i.CreatedAt,
			&i.EmployeeCode,
			&i.Name,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeManualAdjustment = `-- name: RevokeManualAdjustment :exec
UPDATE manual_adjustments
SET status = 'revoked', updated_at = NOW()
WHERE id = ? AND status = 'active'
`

func (q *Queries) RevokeManualAdjustment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeManualAdjustment, id)
	return err
}

const updateManualAdjustment = `-- name: UpdateManualAdjustment :exec
UPDATE manual_adjustments
SET start_at = ?, end_at = ?, reason = ?, note = ?, updated_at = NOW()
WHERE id = ? AND status = 'active'
`

type UpdateManualAdjustmentParams struct {
	StartAt time.Time `json:"start_at"`
	EndAt   time.Time `json:"end_at"`
	Reason  string    `json:"reason"`
	Note    string    `json:"note"`
	ID      int64     `json:"id"`
}

func (q *Queries) UpdateManualAdjustment(ctx context.Context, arg UpdateManualAdjustmentParams) error {
	_, err := q.db.ExecContext(ctx, updateManualAdjustment,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
		arg.Note,
		arg.ID,
	)
	return err
}
