// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type EmployeesLastStatus string

const (
	EmployeesLastStatusWork   EmployeesLastStatus = "work"
	EmployeesLastStatusNormal EmployeesLastStatus = "normal"
	EmployeesLastStatusFish   EmployeesLastStatus = "fish"
	EmployeesLastStatusIdle   EmployeesLastStatus = "idle"
)

func (e *EmployeesLastStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmployeesLastStatus(s)
	case string:
		*e = EmployeesLastStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EmployeesLastStatus: %T", src)
	}
	return nil
}

type NullEmployeesLastStatus struct {
	EmployeesLastStatus EmployeesLastStatus `json:"employees_last_status"`
	Valid               bool                `json:"valid"` // Valid is true if EmployeesLastStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmployeesLastStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EmployeesLastStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmployeesLastStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmployeesLastStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmployeesLastStatus), nil
}

type ManualAdjustmentsStatus string

const (
	ManualAdjustmentsStatusActive  ManualAdjustmentsStatus = "active"
	ManualAdjustmentsStatusRevoked ManualAdjustmentsStatus = "revoked"
)

func (e *ManualAdjustmentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ManualAdjustmentsStatus(s)
	case string:
		*e = ManualAdjustmentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ManualAdjustmentsStatus: %T", src)
	}
	return nil
}

type NullManualAdjustmentsStatus struct {
	ManualAdjustmentsStatus ManualAdjustmentsStatus `json:"manual_adjustments_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if ManualAdjustmentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManualAdjustmentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ManualAdjustmentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ManualAdjustmentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManualAdjustmentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ManualAdjustmentsStatus), nil
}

type RawEventsStatus string

const (
	RawEventsStatusWork   RawEventsStatus = "work"
	RawEventsStatusNormal RawEventsStatus = "normal"
	RawEventsStatusFish   RawEventsStatus = "fish"
	RawEventsStatusIdle   RawEventsStatus = "idle"
)

func (e *RawEventsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RawEventsStatus(s)
	case string:
		*e = RawEventsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RawEventsStatus: %T", src)
	}
	return nil
}

type NullRawEventsStatus struct {
	RawEventsStatus RawEventsStatus `json:"raw_events_status"`
	Valid           bool            `json:"valid"` // Valid is true if RawEventsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRawEventsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RawEventsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RawEventsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRawEventsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RawEventsStatus), nil
}

type RulesMatchMode string

const (
	RulesMatchModeProcess RulesMatchMode = "process"
	RulesMatchModeTitle   RulesMatchMode = "title"
)

func (e *RulesMatchMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RulesMatchMode(s)
	case string:
		*e = RulesMatchMode(s)
	default:
		return fmt.Errorf("unsupported scan type for RulesMatchMode: %T", src)
	}
	return nil
}

type NullRulesMatchMode struct {
	RulesMatchMode RulesMatchMode `json:"rules_match_mode"`
	Valid          bool           `json:"valid"` // Valid is true if RulesMatchMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRulesMatchMode) Scan(value interface{}) error {
	if value == nil {
		ns.RulesMatchMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RulesMatchMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRulesMatchMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RulesMatchMode), nil
}

type RulesRuleType string

const (
	RulesRuleTypeWhite RulesRuleType = "white"
	RulesRuleTypeBlack RulesRuleType = "black"
)

func (e *RulesRuleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RulesRuleType(s)
	case string:
		*e = RulesRuleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RulesRuleType: %T", src)
	}
	return nil
}

type NullRulesRuleType struct {
	RulesRuleType RulesRuleType `json:"rules_rule_type"`
	Valid         bool          `json:"valid"` // Valid is true if RulesRuleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRulesRuleType) Scan(value interface{}) error {
	if value == nil {
		ns.RulesRuleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RulesRuleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRulesRuleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RulesRuleType), nil
}

type TimeSegmentsSource string

const (
	TimeSegmentsSourceSystem   TimeSegmentsSource = "system"
	TimeSegmentsSourceOffline  TimeSegmentsSource = "offline"
	TimeSegmentsSourceManual   TimeSegmentsSource = "manual"
	TimeSegmentsSourceIncident TimeSegmentsSource = "incident"
)

func (e *TimeSegmentsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeSegmentsSource(s)
	case string:
		*e = TimeSegmentsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeSegmentsSource: %T", src)
	}
	return nil
}

type NullTimeSegmentsSource struct {
	TimeSegmentsSource TimeSegmentsSource `json:"time_segments_source"`
	Valid              bool               `json:"valid"` // Valid is true if TimeSegmentsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeSegmentsSource) Scan(value interface{}) error {
	if value == nil {
		ns.TimeSegmentsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeSegmentsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeSegmentsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeSegmentsSource), nil
}

type TimeSegmentsStatus string

const (
	TimeSegmentsStatusWork     TimeSegmentsStatus = "work"
	TimeSegmentsStatusNormal   TimeSegmentsStatus = "normal"
	TimeSegmentsStatusFish     TimeSegmentsStatus = "fish"
	TimeSegmentsStatusIdle     TimeSegmentsStatus = "idle"
	TimeSegmentsStatusOffline  TimeSegmentsStatus = "offline"
	TimeSegmentsStatusIncident TimeSegmentsStatus = "incident"
)

func (e *TimeSegmentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeSegmentsStatus(s)
	case string:
		*e = TimeSegmentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeSegmentsStatus: %T", src)
	}
	return nil
}

type NullTimeSegmentsStatus struct {
	TimeSegmentsStatus TimeSegmentsStatus `json:"time_segments_status"`
	Valid              bool               `json:"valid"` // Valid is true if TimeSegmentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeSegmentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TimeSegmentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeSegmentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeSegmentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeSegmentsStatus), nil
}

type AdminSession struct {
	Token     string       `json:"token"`
	AdminID   int64        `json:"admin_id"`
	IssuedAt  time.Time    `json:"issued_at"`
	ExpiresAt sql.NullTime `json:"expires_at"`
	Revoked   bool         `json:"revoked"`
	LastSeen  sql.NullTime `json:"last_seen"`
}

type AdminUser struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type AuditLog struct {
	ID         int64           `json:"id"`
	OperatorID int64           `json:"operator_id"`
	Action     string          `json:"action"`
	TargetType string          `json:"target_type"`
	TargetID   sql.NullInt64   `json:"target_id"`
	Detail     json.RawMessage `json:"detail"`
	CreatedAt  time.Time       `json:"created_at"`
}

type ClientToken struct {
	Token      string       `json:"token"`
	EmployeeID int64        `json:"employee_id"`
	IssuedAt   time.Time    `json:"issued_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	Revoked    bool         `json:"revoked"`
	LastSeen   sql.NullTime `json:"last_seen"`
}

type DailyStat struct {
	ID                int64     `json:"id"`
	StatDate          time.Time `json:"stat_date"`
	EmployeeID        int64     `json:"employee_id"`
	WorkSeconds       int32     `json:"work_seconds"`
	NormalSeconds     int32     `json:"normal_seconds"`
	FishSeconds       int32     `json:"fish_seconds"`
	IdleSeconds       int32     `json:"idle_seconds"`
	OfflineSeconds    int32     `json:"offline_seconds"`
	AttendanceSeconds int32     `json:"attendance_seconds"`
	EffectiveSeconds  int32     `json:"effective_seconds"`
}

type Department struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	ParentID  sql.NullInt64 `json:"parent_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Employee struct {
	ID               int64                   `json:"id"`
	EmployeeCode     string                  `json:"employee_code"`
	Name             string                  `json:"name"`
	DepartmentID     sql.NullInt64           `json:"department_id"`
	FingerprintHash  sql.NullString          `json:"fingerprint_hash"`
	Enabled          bool                    `json:"enabled"`
	LastSeenAt       sql.NullTime            `json:"last_seen_at"`
	LastStatus       NullEmployeesLastStatus `json:"last_status"`
	LastDescription  sql.NullString          `json:"last_description"`
	LastSegmentEndAt sql.NullTime            `json:"last_segment_end_at"`
	CreatedAt        time.Time               `json:"created_at"`
}

type WorkSession struct {
	ID         int64        `json:"id"`
	EmployeeID int64        `json:"employee_id"`
	StartAt    time.Time    `json:"start_at"`
	EndAt      sql.NullTime `json:"end_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type ManualAdjustment struct {
	ID         int64                   `json:"id"`
	EmployeeID int64                   `json:"employee_id"`
	StartAt    time.Time               `json:"start_at"`
	EndAt      time.Time               `json:"end_at"`
	Reason     string                  `json:"reason"`
	Note       string                  `json:"note"`
	OperatorID int64                   `json:"operator_id"`
	Status     ManualAdjustmentsStatus `json:"status"`
	CreatedAt  time.Time               `json:"created_at"`
	UpdatedAt  time.Time               `json:"updated_at"`
}

type RawEvent struct {
	ID            int64           `json:"id"`
	EmployeeID    int64           `json:"employee_id"`
	ReceivedAt    time.Time       `json:"received_at"`
	ProcessName   sql.NullString  `json:"process_name"`
	WindowTitle   sql.NullString  `json:"window_title"`
	IdleSeconds   int32           `json:"idle_seconds"`
	Status        RawEventsStatus `json:"status"`
	ClientVersion sql.NullString  `json:"client_version"`
	IpAddress     sql.NullString  `json:"ip_address"`
}

type Rule struct {
	ID         int64          `json:"id"`
	RuleType   RulesRuleType  `json:"rule_type"`
	MatchMode  RulesMatchMode `json:"match_mode"`
	MatchValue string         `json:"match_value"`
	Enabled    bool           `json:"enabled"`
	Remark     sql.NullString `json:"remark"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Setting struct {
	ID                       int8           `json:"id"`
	IdleThresholdSeconds     int32          `json:"idle_threshold_seconds"`
	HeartbeatIntervalSeconds int32          `json:"heartbeat_interval_seconds"`
	OfflineThresholdSeconds  int32          `json:"offline_threshold_seconds"`
	FishRatioWarnPercent     int32          `json:"fish_ratio_warn_percent"`
	UpdatePolicy             int8           `json:"update_policy"`
	LatestVersion            sql.NullString `json:"latest_version"`
	UpdateUrl                sql.NullString `json:"update_url"`
	UpdatedAt                time.Time      `json:"updated_at"`
}

type SystemIncident struct {
	ID        int64          `json:"id"`
	StartAt   time.Time      `json:"start_at"`
	EndAt     time.Time      `json:"end_at"`
	Reason    string         `json:"reason"`
	Note      sql.NullString `json:"note"`
	CreatedAt time.Time      `json:"created_at"`
}

type TimeSegment struct {
	ID          int64              `json:"id"`
	EmployeeID  int64              `json:"employee_id"`
	StartAt     time.Time          `json:"start_at"`
	EndAt       time.Time          `json:"end_at"`
	Status      TimeSegmentsStatus `json:"status"`
	Description sql.NullString     `json:"description"`
	Source      TimeSegmentsSource `json:"source"`
	CreatedAt   time.Time          `json:"created_at"`
}

