// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddDailyStats(ctx context.Context, arg AddDailyStatsParams) error
	ClearEmployeeFingerprint(ctx context.Context, id int64) error
	CountAdminUsers(ctx context.Context) (int64, error)
	CountEmployeesByDepartment(ctx context.Context, departmentID sql.NullInt64) (int64, error)
	CountNonOfflineSegmentsOverlap(ctx context.Context, arg CountNonOfflineSegmentsOverlapParams) (int64, error)
	CountOfflineSegmentsCover(ctx context.Context, arg CountOfflineSegmentsCoverParams) (int64, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) error
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error
	GetMaxAutoEmployeeCodeNumber(ctx context.Context) (int64, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (sql.Result, error)
	CreateManualAdjustment(ctx context.Context, arg CreateManualAdjustmentParams) (sql.Result, error)
	CreateRawEvent(ctx context.Context, arg CreateRawEventParams) error
	CreateRule(ctx context.Context, arg CreateRuleParams) (sql.Result, error)
	CreateTimeSegment(ctx context.Context, arg CreateTimeSegmentParams) error
	CreateWorkSession(ctx context.Context, arg CreateWorkSessionParams) error
	CloseWorkSession(ctx context.Context, arg CloseWorkSessionParams) error
	GetOpenWorkSessionByEmployee(ctx context.Context, employeeID int64) (WorkSession, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) error
	DeleteDepartment(ctx context.Context, id int64) error
	DeleteIncident(ctx context.Context, id int64) error
	DeleteManualSegment(ctx context.Context, arg DeleteManualSegmentParams) error
	DeleteRawEventsBefore(ctx context.Context, receivedAt time.Time) error
	DeleteRule(ctx context.Context, id int64) error
	GetAdminSession(ctx context.Context, token string) (AdminSession, error)
	GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error)
	GetEmployeeByCode(ctx context.Context, employeeCode string) (Employee, error)
	GetEmployeeByID(ctx context.Context, id int64) (Employee, error)
	GetLastRawEventByEmployee(ctx context.Context, employeeID int64) (RawEvent, error)
	GetManualAdjustment(ctx context.Context, id int64) (ManualAdjustment, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetToken(ctx context.Context, token string) (ClientToken, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListDailyStatsByDate(ctx context.Context, arg ListDailyStatsByDateParams) ([]ListDailyStatsByDateRow, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListEmployees(ctx context.Context) ([]ListEmployeesRow, error)
	ListEmployeesAdmin(ctx context.Context) ([]ListEmployeesAdminRow, error)
	ListEmployeesAdminByKeyword(ctx context.Context, arg ListEmployeesAdminByKeywordParams) ([]ListEmployeesAdminByKeywordRow, error)
	ListEmployeesForOfflineRefresh(ctx context.Context) ([]Employee, error)
	ListEnabledRules(ctx context.Context) ([]ListEnabledRulesRow, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]SystemIncident, error)
	ListLiveSnapshot(ctx context.Context) ([]ListLiveSnapshotRow, error)
	ListManualAdjustments(ctx context.Context, arg ListManualAdjustmentsParams) ([]ListManualAdjustmentsRow, error)
	ListOfflineSegmentsByDate(ctx context.Context, arg ListOfflineSegmentsByDateParams) ([]ListOfflineSegmentsByDateRow, error)
	ListOfflineSegmentsByEmployeeAndRange(ctx context.Context, arg ListOfflineSegmentsByEmployeeAndRangeParams) ([]ListOfflineSegmentsByEmployeeAndRangeRow, error)
	ListRules(ctx context.Context) ([]ListRulesRow, error)
	ListTimeSegmentsByEmployeeAndRange(ctx context.Context, arg ListTimeSegmentsByEmployeeAndRangeParams) ([]ListTimeSegmentsByEmployeeAndRangeRow, error)
	RevokeAdminSession(ctx context.Context, token string) error
	RevokeManualAdjustment(ctx context.Context, id int64) error
	RevokeToken(ctx context.Context, token string) error
	RevokeTokensByEmployee(ctx context.Context, employeeID int64) error
	UpdateAdminSessionLastSeen(ctx context.Context, arg UpdateAdminSessionLastSeenParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) error
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
	UpdateEmployeeEnabled(ctx context.Context, arg UpdateEmployeeEnabledParams) error
	UpdateEmployeeFingerprint(ctx context.Context, arg UpdateEmployeeFingerprintParams) error
	UpdateEmployeeLastSeen(ctx context.Context, arg UpdateEmployeeLastSeenParams) error
	UpdateEmployeeLastSegmentEnd(ctx context.Context, arg UpdateEmployeeLastSegmentEndParams) error
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) error
	UpdateManualAdjustment(ctx context.Context, arg UpdateManualAdjustmentParams) error
	UpdateManualSegment(ctx context.Context, arg UpdateManualSegmentParams) error
	UpdateRule(ctx context.Context, arg UpdateRuleParams) error
	UpdateTokenLastSeen(ctx context.Context, arg UpdateTokenLastSeenParams) error
	UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error
}

var _ Querier = (*Queries)(nil)


