// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_events.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRawEvent = `-- name: CreateRawEvent :exec
INSERT INTO raw_events (
  employee_id,
  received_at,
  process_name,
  window_title,
  idle_seconds,
  status,
  client_version,
  ip_address
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRawEventParams struct {
	EmployeeID    int64           `json:"employee_id"`
	ReceivedAt    time.Time       `json:"received_at"`
	ProcessName   sql.NullString  `json:"process_name"`
	WindowTitle   sql.NullString  `json:"window_title"`
	IdleSeconds   int32           `json:"idle_seconds"`
	Status        RawEventsStatus `json:"status"`
	ClientVersion sql.NullString  `json:"client_version"`
	IpAddress     sql.NullString  `json:"ip_address"`
}

func (q *Queries) CreateRawEvent(ctx context.Context, arg CreateRawEventParams) error {
	_, err := q.db.ExecContext(ctx, createRawEvent,
		arg.EmployeeID,
		arg.ReceivedAt,
		arg.ProcessName,
		arg.WindowTitle,
		arg.IdleSeconds,
		arg.Status,
		arg.ClientVersion,
		arg.IpAddress,
	)
	return err
}

const deleteRawEventsBefore = `-- name: DeleteRawEventsBefore :exec
DELETE FROM raw_events
WHERE received_at < ?
`

func (q *Queries) DeleteRawEventsBefore(ctx context.Context, receivedAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRawEventsBefore, receivedAt)
	return err
}

const getLastRawEventByEmployee = `-- name: GetLastRawEventByEmployee :one
SELECT id, employee_id, received_at, process_name, window_title, idle_seconds, status, client_version, ip_address
FROM raw_events
WHERE employee_id = ?
ORDER BY received_at DESC
LIMIT 1
`

func (q *Queries) GetLastRawEventByEmployee(ctx context.Context, employeeID int64) (RawEvent, error) {
	row := q.db.QueryRowContext(ctx, getLastRawEventByEmployee, employeeID)
	var i RawEvent
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.ReceivedAt,
		&i.ProcessName,
		&i.WindowTitle,
		&i.IdleSeconds,
		&i.Status,
		&i.ClientVersion,
		&i.IpAddress,
	)
	return i, err
}
