// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRule = `-- name: CreateRule :execresult
INSERT INTO rules (rule_type, match_mode, match_value, enabled, remark)
VALUES (?, ?, ?, ?, ?)
`

type CreateRuleParams struct {
	RuleType   RulesRuleType  `json:"rule_type"`
	MatchMode  RulesMatchMode `json:"match_mode"`
	MatchValue string         `json:"match_value"`
	Enabled    bool           `json:"enabled"`
	Remark     sql.NullString `json:"remark"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRule,
		arg.RuleType,
		arg.MatchMode,
		arg.MatchValue,
		arg.Enabled,
		arg.Remark,
	)
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const listRules = `-- name: ListRules :many
SELECT id, rule_type, match_mode, match_value, enabled, remark, created_at
FROM rules
ORDER BY id DESC
`

type ListRulesRow struct {
	ID         int64          `json:"id"`
	RuleType   RulesRuleType  `json:"rule_type"`
	MatchMode  RulesMatchMode `json:"match_mode"`
	MatchValue string         `json:"match_value"`
	Enabled    bool           `json:"enabled"`
	Remark     sql.NullString `json:"remark"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) ListRules(ctx context.Context) ([]ListRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRulesRow
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleType,
			&i.MatchMode,
			&i.MatchValue,
			&i.Enabled,
			&i.Remark,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules
SET rule_type = ?, match_mode = ?, match_value = ?, enabled = ?, remark = ?
WHERE id = ?
`

type UpdateRuleParams struct {
	RuleType   RulesRuleType  `json:"rule_type"`
	MatchMode  RulesMatchMode `json:"match_mode"`
	MatchValue string         `json:"match_value"`
	Enabled    bool           `json:"enabled"`
	Remark     sql.NullString `json:"remark"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateRule,
		arg.RuleType,
		arg.MatchMode,
		arg.MatchValue,
		arg.Enabled,
		arg.Remark,
		arg.ID,
	)
	return err
}
