// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules_enabled.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, rule_type, match_mode, match_value, enabled, remark, created_at
FROM rules
WHERE enabled = 1
ORDER BY id DESC
`

type ListEnabledRulesRow struct {
	ID         int64          `json:"id"`
	RuleType   RulesRuleType  `json:"rule_type"`
	MatchMode  RulesMatchMode `json:"match_mode"`
	MatchValue string         `json:"match_value"`
	Enabled    bool           `json:"enabled"`
	Remark     sql.NullString `json:"remark"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) ListEnabledRules(ctx context.Context) ([]ListEnabledRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledRulesRow
	for rows.Next() {
		var i ListEnabledRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleType,
			&i.MatchMode,
			&i.MatchValue,
			&i.Enabled,
			&i.Remark,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
