// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getSettings = `-- name: GetSettings :one
SELECT id, idle_threshold_seconds, heartbeat_interval_seconds, offline_threshold_seconds, fish_ratio_warn_percent, update_policy, latest_version, update_url,
       history_cleanup_enabled, history_retention_days, history_cleanup_hour, history_cleanup_last_run_at, updated_at
FROM settings
WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.IdleThresholdSeconds,
		&i.HeartbeatIntervalSeconds,
		&i.OfflineThresholdSeconds,
		&i.FishRatioWarnPercent,
		&i.UpdatePolicy,
		&i.LatestVersion,
		&i.UpdateUrl,
		&i.HistoryCleanupEnabled,
		&i.HistoryRetentionDays,
		&i.HistoryCleanupHour,
		&i.HistoryCleanupLastRunAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :exec
INSERT INTO settings (
  id,
  idle_threshold_seconds,
  heartbeat_interval_seconds,
  offline_threshold_seconds,
  fish_ratio_warn_percent,
  update_policy,
  latest_version,
  update_url,
  history_cleanup_enabled,
  history_retention_days,
  history_cleanup_hour,
  updated_at
) VALUES (
  1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW()
)
ON DUPLICATE KEY UPDATE
  idle_threshold_seconds = VALUES(idle_threshold_seconds),
  heartbeat_interval_seconds = VALUES(heartbeat_interval_seconds),
  offline_threshold_seconds = VALUES(offline_threshold_seconds),
  fish_ratio_warn_percent = VALUES(fish_ratio_warn_percent),
  update_policy = VALUES(update_policy),
  latest_version = VALUES(latest_version),
  update_url = VALUES(update_url),
  history_cleanup_enabled = VALUES(history_cleanup_enabled),
  history_retention_days = VALUES(history_retention_days),
  history_cleanup_hour = VALUES(history_cleanup_hour),
  updated_at = NOW()
`

type UpsertSettingsParams struct {
	IdleThresholdSeconds     int32          `json:"idle_threshold_seconds"`
	HeartbeatIntervalSeconds int32          `json:"heartbeat_interval_seconds"`
	OfflineThresholdSeconds  int32          `json:"offline_threshold_seconds"`
	FishRatioWarnPercent     int32          `json:"fish_ratio_warn_percent"`
	UpdatePolicy             int8           `json:"update_policy"`
	LatestVersion            sql.NullString `json:"latest_version"`
	UpdateUrl                sql.NullString `json:"update_url"`
	HistoryCleanupEnabled    int8           `json:"history_cleanup_enabled"`
	HistoryRetentionDays     int32          `json:"history_retention_days"`
	HistoryCleanupHour       int8           `json:"history_cleanup_hour"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertSettings,
		arg.IdleThresholdSeconds,
		arg.HeartbeatIntervalSeconds,
		arg.OfflineThresholdSeconds,
		arg.FishRatioWarnPercent,
		arg.UpdatePolicy,
		arg.LatestVersion,
		arg.UpdateUrl,
		arg.HistoryCleanupEnabled,
		arg.HistoryRetentionDays,
		arg.HistoryCleanupHour,
	)
	return err
}
