// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_incidents.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createIncident = `-- name: CreateIncident :execresult
INSERT INTO system_incidents (start_at, end_at, reason, note)
VALUES (?, ?, ?, ?)
`

type CreateIncidentParams struct {
	StartAt time.Time      `json:"start_at"`
	EndAt   time.Time      `json:"end_at"`
	Reason  string         `json:"reason"`
	Note    sql.NullString `json:"note"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createIncident,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
		arg.Note,
	)
}

const deleteIncident = `-- name: DeleteIncident :exec
DELETE FROM system_incidents WHERE id = ?
`

func (q *Queries) DeleteIncident(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncident, id)
	return err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, start_at, end_at, reason, note, created_at
FROM system_incidents
WHERE ( ? = '' OR DATE(start_at) = ? )
ORDER BY start_at DESC
`

type ListIncidentsParams struct {
	Column1 interface{} `json:"column_1"`
	StartAt time.Time   `json:"start_at"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]SystemIncident, error) {
	rows, err := q.db.QueryContext(ctx, listIncidents, arg.Column1, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemIncident
	for rows.Next() {
		var i SystemIncident
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.Reason,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncident = `-- name: UpdateIncident :exec
UPDATE system_incidents
SET start_at = ?, end_at = ?, reason = ?, note = ?
WHERE id = ?
`

type UpdateIncidentParams struct {
	StartAt time.Time      `json:"start_at"`
	EndAt   time.Time      `json:"end_at"`
	Reason  string         `json:"reason"`
	Note    sql.NullString `json:"note"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) error {
	_, err := q.db.ExecContext(ctx, updateIncident,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
		arg.Note,
		arg.ID,
	)
	return err
}
