// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO client_tokens (token, employee_id, issued_at, expires_at, revoked, last_seen)
VALUES (?, ?, ?, ?, 0, ?)
`

type CreateTokenParams struct {
	Token      string       `json:"token"`
	EmployeeID int64        `json:"employee_id"`
	IssuedAt   time.Time    `json:"issued_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
	LastSeen   sql.NullTime `json:"last_seen"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.Token,
		arg.EmployeeID,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastSeen,
	)
	return err
}

const getToken = `-- name: GetToken :one
SELECT token, employee_id, issued_at, expires_at, revoked, last_seen
FROM client_tokens
WHERE token = ?
LIMIT 1
`

func (q *Queries) GetToken(ctx context.Context, token string) (ClientToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i ClientToken
	err := row.Scan(
		&i.Token,
		&i.EmployeeID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.LastSeen,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE client_tokens
SET revoked = 1
WHERE token = ?
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}

const revokeTokensByEmployee = `-- name: RevokeTokensByEmployee :exec
UPDATE client_tokens
SET revoked = 1
WHERE employee_id = ?
`

func (q *Queries) RevokeTokensByEmployee(ctx context.Context, employeeID int64) error {
	_, err := q.db.ExecContext(ctx, revokeTokensByEmployee, employeeID)
	return err
}

const updateTokenLastSeen = `-- name: UpdateTokenLastSeen :exec
UPDATE client_tokens
SET last_seen = ?
WHERE token = ?
`

type UpdateTokenLastSeenParams struct {
	LastSeen sql.NullTime `json:"last_seen"`
	Token    string       `json:"token"`
}

func (q *Queries) UpdateTokenLastSeen(ctx context.Context, arg UpdateTokenLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateTokenLastSeen, arg.LastSeen, arg.Token)
	return err
}
