// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createWorkSession = `-- name: CreateWorkSession :exec
INSERT INTO work_sessions (
  employee_id,
  start_at,
  end_at
) VALUES (?, ?, NULL)
`

type CreateWorkSessionParams struct {
	EmployeeID int64     `json:"employee_id"`
	StartAt    time.Time `json:"start_at"`
}

func (q *Queries) CreateWorkSession(ctx context.Context, arg CreateWorkSessionParams) error {
	_, err := q.db.ExecContext(ctx, createWorkSession,
		arg.EmployeeID,
		arg.StartAt,
	)
	return err
}

const closeWorkSession = `-- name: CloseWorkSession :exec
UPDATE work_sessions
SET end_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE employee_id = ?
  AND end_at IS NULL
ORDER BY start_at DESC
LIMIT 1
`

type CloseWorkSessionParams struct {
	EndAt      time.Time `json:"end_at"`
	EmployeeID int64     `json:"employee_id"`
}

func (q *Queries) CloseWorkSession(ctx context.Context, arg CloseWorkSessionParams) error {
	_, err := q.db.ExecContext(ctx, closeWorkSession,
		arg.EndAt,
		arg.EmployeeID,
	)
	return err
}

const getOpenWorkSessionByEmployee = `-- name: GetOpenWorkSessionByEmployee :one
SELECT id, employee_id, start_at, end_at, created_at, updated_at
FROM work_sessions
WHERE employee_id = ?
  AND end_at IS NULL
ORDER BY start_at DESC
LIMIT 1
`

func (q *Queries) GetOpenWorkSessionByEmployee(ctx context.Context, employeeID int64) (WorkSession, error) {
	row := q.db.QueryRowContext(ctx, getOpenWorkSessionByEmployee, employeeID)
	var i WorkSession
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

var _ = sql.ErrNoRows
